production:
  adapter: mysql2
  encoding: utf8
  database: owm_db
  pool: 5
  username: owm_db_user
  host: localhost




development:
  adapter: mysql2
  encoding: utf8
  database: owm_db
  pool: 5
  username: owm_db_user
  host: localhost




test:
  adapter: mysql2
  encoding: utf8
  database: owm_db
  pool: 5
  username: owm_db_user
  host: localhost



